In [5]:
from sqlalchemy import create_engine, Column, Integer, String, Boolean, Float, ForeignKey, ForeignKeyConstraint, BigInteger, TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import DataError, IntegrityError

import pandas as pd

In [6]:
Base = declarative_base()

C:\Users\arian\AppData\Local\Temp\ipykernel_18392\4196137762.py:1: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [7]:
class MatchEventInfo(Base):
    __tablename__ = 'match_event_info'
    match_id = Column(BigInteger, primary_key=True)
    first_to_serve = Column(Integer)
    home_team_seed = Column(String)
    away_team_seed = Column(String)
    custom_id = Column(String)
    winner_code = Column(Integer)
    default_period_count = Column(Integer)
    start_datetime = Column(Integer)
    match_slug = Column(String)
    final_result_only = Column(Boolean)

class MatchVotesInfo(Base):
    __tablename__ = 'match_votes_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    home_vote = Column(Integer)
    away_vote = Column(Integer)

class MatchTournamentInfo(Base):
    __tablename__ = 'match_tournament_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    tournament_id = Column(Integer)
    tournament_name = Column(String)
    tournament_slug = Column(String)
    tournament_unique_id = Column(String)
    tournament_category_name = Column(String)
    tournament_category_slug = Column(String)
    user_count = Column(Integer)
    ground_type = Column(String)
    tennis_points = Column(Float)
    has_event_player_statistics = Column(Boolean)
    crowd_sourcing_enabled = Column(Boolean)
    has_performance_graph_feature = Column(Boolean)
    display_inverse_home_away_teams = Column(Boolean)
    priority = Column(Integer)
    competition_type = Column(Integer)

class MatchSeasonInfo(Base):
    __tablename__ = 'match_season_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    season_id = Column(Integer)
    name = Column(String)
    year = Column(Integer)

class MatchRoundInfo(Base):
    __tablename__ = 'match_round_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    round_id = Column(Integer)
    name = Column(String)
    slug = Column(String)
    cup_round_type = Column(Integer)

class MatchVenueInfo(Base):
    __tablename__ = 'match_venue_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    city = Column(String)
    stadium = Column(String)
    venue_id = Column(Integer)
    country = Column(String)

class MatchHomeTeamInfo(Base):
    __tablename__ = 'match_home_team_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    name = Column(String)
    slug = Column(String)
    gender = Column(String)
    user_count = Column(Integer)
    residence = Column(String)
    birthplace = Column(String)
    height = Column(Float)
    weight = Column(Integer)
    plays = Column(String)
    turned_pro = Column(Integer)
    current_prize = Column(Integer)
    total_prize = Column(Integer)
    player_id = Column(Integer)
    current_rank = Column(Integer)
    name_code = Column(String)
    country = Column(String)
    full_name = Column(String)

class MatchAwayTeamInfo(Base):
    __tablename__ = 'match_away_team_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    name = Column(String)
    slug = Column(String)
    gender = Column(String)
    user_count = Column(Integer)
    residence = Column(String)
    birthplace = Column(String)
    height = Column(Float)
    weight = Column(Integer)
    plays = Column(String)
    turned_pro = Column(Integer)
    current_prize = Column(Integer)
    total_prize = Column(Integer)
    player_id = Column(Integer)
    current_rank = Column(Integer)
    name_code = Column(String)
    country = Column(String)
    full_name = Column(String)

class MatchHomeScoreInfo(Base):
    __tablename__ = 'match_home_score_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    current_score = Column(Integer)
    display_score = Column(Integer)
    period_1 = Column(Integer)
    period_2 = Column(Integer)
    period_3 = Column(Integer)
    period_4 = Column(Integer)
    period_5 = Column(Integer)
    period_1_tie_break = Column(Integer)
    period_2_tie_break = Column(Integer)
    period_3_tie_break = Column(Integer)
    period_4_tie_break = Column(Integer)
    period_5_tie_break = Column(Integer)
    normal_time = Column(Integer)

class MatchAwayScoreInfo(Base):
    __tablename__ = 'match_away_score_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    current_score = Column(Integer)
    display_score = Column(Integer)
    period_1 = Column(Integer)
    period_2 = Column(Integer)
    period_3 = Column(Integer)
    period_4 = Column(Integer)
    period_5 = Column(Integer)
    period_1_tie_break = Column(Integer)
    period_2_tie_break = Column(Integer)
    period_3_tie_break = Column(Integer)
    period_4_tie_break = Column(Integer)
    period_5_tie_break = Column(Integer)
    normal_time = Column(Integer)

class MatchTimeInfo(Base):
    __tablename__ = 'match_time_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    period_1 = Column(Integer)
    period_2 = Column(Integer)
    period_3 = Column(Integer)
    period_4 = Column(Integer)
    period_5 = Column(Integer)
    current_period_start_timestamp = Column(BigInteger)

class GameInfo(Base):
    __tablename__ = 'game_info'
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'), primary_key=True)
    set_id = Column(Integer, primary_key=True)
    game_id = Column(Integer, primary_key=True)
    point_id = Column(Integer, primary_key=True)
    home_point = Column(String)
    away_point = Column(String)
    point_description = Column(Integer)
    home_point_type = Column(Integer)
    away_point_type = Column(Integer)
    home_score = Column(Integer)
    away_score = Column(Integer)
    serving = Column(Integer)  
    scoring = Column(Integer)

class OddsInfo(Base):
    __tablename__ = 'odds_info'
    id = Column(Integer, primary_key=True)
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'))
    market_id = Column(Integer)
    market_name = Column(String)
    is_live = Column(Boolean)
    suspended = Column(Boolean)
    initial_fractional_value = Column(String)
    fractional_value = Column(String)
    choice_name = Column(String)
    choice_source_id = Column(Integer)
    winnig = Column(Boolean)
    change = Column(Integer)

class PowerInfo(Base):
    __tablename__ = 'power_info'
    id = Column(Integer, primary_key=True)
    match_id = Column(Integer, ForeignKey('match_event_info.match_id'))
    set_num = Column(Integer)
    game_num = Column(Integer)
    value = Column(Float)
    break_occurred = Column(Boolean)

-2,147,483,648 to 2,147,483,647

-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.

In [8]:
engine = create_engine('postgresql+psycopg2://postgres:Hitman.agent47@localhost:5432/tennis')
Base.metadata.create_all(engine)

In [9]:
def load_event_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)
    df['first_to_serve'] = pd.to_numeric(df['first_to_serve'], errors='coerce').astype('Int64')  # Use 'Int64' (capital I) to support NaN -> None conversion
    df['winner_code'] = pd.to_numeric(df['winner_code'], errors='coerce').astype('Int64')
    df['default_period_count'] = pd.to_numeric(df['default_period_count'], errors='coerce').astype('Int64')
    df['start_datetime'] = pd.to_numeric(df['start_datetime'], errors='coerce').astype('Int64')
    df = df.where(pd.notnull(df), None)
    
    # Convert DataFrame to list of dictionaries
    records = df.to_dict(orient='records')
    # Bulk insert
    try:
        # Bulk insert
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [10]:
load_event_csv(MatchEventInfo, 'tennis_csv/df_event.csv')

In [11]:
def load_votes_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)
    df = df.where(pd.notnull(df), None)
    
    # Convert DataFrame to list of dictionaries
    records = df.to_dict(orient='records')
    
    # Bulk insert
    try:
        # Bulk insert
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [12]:
load_votes_csv(MatchVotesInfo, 'tennis_csv/df_votes.csv')

In [13]:
def load_tournament_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    max_int_value = 2**31 - 1
    min_int_value = -2**31
    df = pd.read_csv(csv_file)
    df['tennis_points'] = df['tennis_points'].fillna(0)  # Fill NaNs with 0 for tennis_points
    df['tennis_points'] = df['tennis_points'].astype(int)  # Convert to integer
    print(df.tennis_points.unique())
    # Handle integer fields including conversion of tennis_points to integers
    int_columns = ['tournament_id', 'user_count', 'priority', 'competition_type', 'match_id', 'tennis_points']
    
    # Convert tennis_points to integers with appropriate handling of NaN values and rounding
    for col in int_columns:
        if not df[col].between(min_int_value, max_int_value, inclusive="both").all():
            print(f"Column {col} contains out-of-range values.")
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')  # Convert to pandas nullable integer type, allows for NaN -> None

    # Convert NaNs (now coerced to None for int fields, converted to default for tennis_points) to None for other fields
    df = df.where(pd.notnull(df), None)

    records = df.to_dict(orient='records')

    try:
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [14]:
load_tournament_csv(MatchTournamentInfo, 'tennis_csv/df_tournament.csv')

[ 125   75  500  250 1000    0  100]

In [15]:
def load_season_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)
    df = df.where(pd.notnull(df), None)
    
    # Convert DataFrame to list of dictionaries
    records = df.to_dict(orient='records')
    
    # Bulk insert
    try:
        # Bulk insert
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [16]:
load_season_csv(MatchSeasonInfo, 'tennis_csv/df_season.csv')

In [17]:
def load_round_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)
    df['cup_round_type'] = df['cup_round_type'].fillna(0) 
    df = df.where(pd.notnull(df), None)
    
    # Convert DataFrame to list of dictionaries
    records = df.to_dict(orient='records')
    
    # Bulk insert
    try:
        # Bulk insert
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [18]:
load_round_csv(MatchRoundInfo, 'tennis_csv/df_round.csv')

In [19]:
def load_venue_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)
    df = df.where(pd.notnull(df), None)
    # Convert DataFrame to list of dictionaries
    records = df.to_dict(orient='records')
    
    # Bulk insert
    try:
        # Bulk insert
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [20]:
load_venue_csv(MatchVenueInfo, 'tennis_csv/df_venue.csv')

In [21]:
def load_home_info_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)

    # Fill NaNs with 0 for integer columns and ensure they are integers
    int_columns = ['user_count', 'weight', 'turned_pro', 'current_prize', 'total_prize', 'player_id', 'current_rank']
    for col in int_columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype('Int64')  # Handles NaN -> None conversion for Int64

    # Ensure height is treated as a float and NaNs are set to a default value, e.g., 0.0
    df['height'] = pd.to_numeric(df['height'], errors='coerce').fillna(0.0)

    df = df.where(pd.notnull(df), None)  # Convert any remaining NaNs to None

    records = df.to_dict(orient='records')

    for record in records:
        try:
            session.bulk_insert_mappings(table_class, [record])
            session.commit()
        except DataError as e:
            print(f"DataError occurred with record: {record}")
            print(f"Error details: {e}")
            session.rollback()
        except Exception as e:
            print(f"An unexpected error occurred with record: {record}")
            print(f"Error details: {e}")
            session.rollback()

    session.close()

In [22]:
load_home_info_csv(MatchHomeTeamInfo, 'tennis_csv/df_home_team.csv')

In [23]:
load_home_info_csv(MatchAwayTeamInfo, 'tennis_csv/df_away_team.csv')

In [24]:
def load_home_score_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)

    # Specify columns to convert to integers, assuming all score-related columns are to be integers
    int_columns = [
        'current_score', 'display_score', 'period_1', 'period_2', 'period_3',
        'period_4', 'period_5', 'period_1_tie_break', 'period_2_tie_break',
        'period_3_tie_break', 'period_4_tie_break', 'period_5_tie_break', 'normal_time'
    ]

    # Convert specified columns to integers, replacing NaNs with 0
    for column in int_columns:
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0).astype(int)

    records = df.to_dict(orient='records')

    try:
        # Attempt to bulk insert all records
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        print(f"DataError occurred: {e}")
        session.rollback()
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        session.rollback()
    finally:
        session.close()

In [25]:
load_home_score_csv(MatchHomeScoreInfo, 'tennis_csv/df_home_team_score.csv')

In [26]:
load_home_score_csv(MatchAwayScoreInfo, 'tennis_csv/df_away_team_score.csv')

In [27]:
def load_time_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)

    # Columns to convert to integers, including handling NaN values
    integer_columns = ['period_1', 'period_2', 'period_3', 'period_4', 'period_5', 'current_period_start_timestamp']

    # Convert specified columns to integers, replacing NaNs with 0
    for column in integer_columns:
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0).astype(int)

    # Ensure 'match_id' is also an integer (if not already)
    df['match_id'] = df['match_id'].astype(int)

    records = df.to_dict(orient='records')

    try:
        session.bulk_insert_mappings(table_class, records)
        session.commit()
    except DataError as e:
        session.rollback()
        print(f"DataError occurred: {e}")
    except Exception as e:
        session.rollback()
        print(f"An unexpected error occurred: {e}")
    finally:
        session.close()

In [28]:
load_time_csv(MatchTimeInfo, 'tennis_csv/df_time.csv')

In [29]:
def load_game_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)

    # Since 'home_point' and 'away_point' are strings, ensure they are converted to strings properly
    df['home_point'] = df['home_point'].astype(str)
    df['away_point'] = df['away_point'].astype(str)

    # Convert numeric fields to integers, ensuring NaN values are handled (if any)
    numeric_fields = ['point_description', 'home_point_type', 'away_point_type', 'home_score', 'away_score', 'serving', 'scoring']
    for field in numeric_fields:
        if field in df.columns:
            df[field] = pd.to_numeric(df[field], errors='coerce').fillna(0).astype(int)
    
    # Convert 'match_id', 'set_id', 'game_id', and 'point_id' to integers explicitly to match the primary key requirement
    df['match_id'] = df['match_id'].astype(int)
    df['set_id'] = df['set_id'].astype(int)
    df['game_id'] = df['game_id'].astype(int)
    df['point_id'] = df['point_id'].astype(int)

    records = df.to_dict(orient='records')

    try:
        # Attempt to insert records one by one for better error handling
        for record in records:
            session.bulk_insert_mappings(table_class, [record])
            session.commit()
    except DataError as e:
        session.rollback()
        print(f"DataError occurred: {e}")
    except IntegrityError as e:
        session.rollback()
        print(f"IntegrityError (possible duplicate or foreign key constraint violation): {e}")
    except Exception as e:
        session.rollback()
        print(f"An unexpected error occurred: {e}")
    finally:
        session.close()

In [30]:
load_game_csv(GameInfo, 'tennis_csv/df_pbp.csv')

In [31]:
import numpy as np

In [32]:
def load_odd_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)

    mask = df['winnig'].isna()
    sequence_length = mask.sum()
    alternating_sequence = np.empty(sequence_length, dtype=bool)
    alternating_sequence[::2] = False  # Assign False to even indices
    alternating_sequence[1::2] = True  # Assign True to odd indices

    df.loc[mask, 'winnig'] = alternating_sequence
    

    records = df.to_dict(orient='records')

    try:
        # Attempt to insert records one by one for better error handling
        for record in records:
            session.bulk_insert_mappings(table_class, [record])
            session.commit()
    except DataError as e:
        session.rollback()
        print(f"DataError occurred: {e}")
    except IntegrityError as e:
        session.rollback()
        print(f"IntegrityError (possible duplicate or foreign key constraint violation): {e}")
    except Exception as e:
        session.rollback()
        print(f"An unexpected error occurred: {e}")
    finally:
        session.close()

In [33]:
load_odd_csv(OddsInfo, 'tennis_csv/df_odds.csv')

In [35]:
def load_power_csv(table_class, csv_file, engine=engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    df = pd.read_csv(csv_file)

    records = df.to_dict(orient='records')

    try:
        # Attempt to insert records one by one for better error handling
        for record in records:
            session.bulk_insert_mappings(table_class, [record])
            session.commit()
    except DataError as e:
        session.rollback()
        print(f"DataError occurred: {e}")
    except IntegrityError as e:
        session.rollback()
        print(f"IntegrityError (possible duplicate or foreign key constraint violation): {e}")
    except Exception as e:
        session.rollback()
        print(f"An unexpected error occurred: {e}")
    finally:
        session.close()

In [36]:
load_power_csv(PowerInfo, 'tennis_csv/df_power.csv')

In [34]:
df = pd.read_csv('tennis_csv/df_pbp.csv')
df.head()

,match_id,set_id,game_id,point_id,home_point,away_point,point_description,home_point_type,away_point_type,home_score,away_score,serving,scoring
0,11674074,2,7,0,0,15,2,5,1,6,1,1,1
1,11674074,2,7,1,0,30,0,5,1,6,1,1,1
2,11674074,2,7,2,15,30,1,1,5,6,1,1,1
3,11674074,2,7,3,30,30,0,1,5,6,1,1,1
4,11674074,2,7,4,40,30,0,3,5,6,1,1,1